/**
 * SGND - Static Data Configuration
 * Contains dropdown options for forms
 */

const SGND_DATA = {
    // Estados para el Ujier al registrar diligencia
    ESTADOS_DILIGENCIA: [
        { value: 'atiende', label: 'Atiende' },
        { value: 'no_atiende', label: 'No Atiende' },
        { value: 'pre_aviso', label: 'Pre Aviso' },
        { value: 'estrados', label: 'Estrados' },
        { value: 'domicilio_inexistente', label: 'Domicilio Inexistente' },
        { value: 'diligenciador_ausente', label: 'Diligenciador Ausente' }
    ],

    // Provincias para Ley 22.172
    PROVINCIAS: [
        'Buenos Aires',
        'Catamarca',
        'Chaco',
        'Chubut',
        'Ciudad Autónoma de Buenos Aires (CABA)',
        'Córdoba',
        'Corrientes',
        'Entre Ríos',
        'Formosa',
        'Jujuy',
        'La Pampa',
        'La Rioja',
        'Mendoza',
        'Misiones',
        'Neuquén',
        'Río Negro',
        'Salta',
        'San Juan',
        'San Luis',
        'Santa Cruz',
        'Santa Fe',
        'Santiago del Estero',
        'Tierra del Fuego, Antártida e Islas del Atlántico Sur',
        'Tucumán'
    ],

    // Localidades de Catamarca para correspondencia
    LOCALIDADES_CATAMARCA: [
        'ACHALCO - EL ALTO',
        'ACONQUIJA - ANDALGALÁ',
        'ADOLFO E. CARRANZA - CAPAYAN',
        'AGUA AMARILLA - SANTA MARIA',
        'AGUA COLORADA - VALLE VIEJO',
        'AGUA DE LAS PALOMAS - ANDALGALÁ',
        'AGUA NEGRA - TINOGASTA',
        'AGUA VERDE - ANDALGALÁ',
        'ALBIGASTA - EL ALTO',
        'ALIJILAN - SANTA ROSA',
        'ALTA GRACIA - SANTA ROSA',
        'ALTO DE LAS JUNTAS - ANDALGALÁ',
        'ALTO EL BOLSON - BELEN',
        'AMADORES - PACLIN',
        'AMANA - ANCASTI',
        'AMANAO - ANDALGALÁ',
        'AMPAJANGO - SANTA MARIA',
        'AMPOLLA - SANTA ROSA',
        'AMPUJACO - BELEN',
        'ANCASTI - ANCASTI',
        'ANCASTILLO - LA PAZ',
        'ANDALGALA - ANDALGALÁ',
        'ANDALHUALA - SANTA MARIA',
        'ANILLACO - TINOGASTA',
        'ANJULI - LA PAZ',
        'ANQUINCILA - ANCASTI',
        'ANTAPOCA - VALLE VIEJO',
        'ANTINACO - TINOGASTA',
        'ANTOFAGASTA DE LA SIERRA - ANTOFAGASTA DE LA SIERRA',
        'ANTOFALLA - ANTOFAGASTA DE LA SIERRA',
        'ANTOFALLITA - ANTOFAGASTA DE LA SIERRA',
        'APOYACO - POMAN',
        'ASAMPAY - BELEN',
        'AYAPASO - EL ALTO',
        'BALDE DE LA PAMPA - POMAN',
        'BALDE DE LA PUNTA - CAPAYAN',
        'BANDA DE LUCERO - TINOGASTA',
        'BAÑADO DE OVANTA - SANTA ROSA',
        'BARRANCA LARGA - BELEN',
        'BARRANCA MOLLE - ANDALGALÁ',
        'BARRIO ARTAZA - BELEN',
        'BARRO NEGRO - PACLIN',
        'BAVIANO - LA PAZ',
        'BELEN - BELEN',
        'BELLA VISTA - EL ALTO',
        'BUENA VISTA - ANDALGALÁ',
        'CABALLA - LA PAZ',
        'CACHIYUYO - TINOGASTA',
        'CAMPO ALEGRE - SANTA ROSA',
        'CAMPO DE LAS CALIVAS - BELEN',
        'CAPAYAN - CAPAYAN',
        'CARACHI PAMPA - ANTOFAGASTA DE LA SIERRA',
        'CARRANZA - CAPAYAN',
        'CASA ARMADA - ANCASTI',
        'CASA DE ALTO - TINOGASTA',
        'CASA DE PIEDRA - LA PAZ',
        'CASA DE PIEDRA - SANTA MARIA',
        'CASA DEL CAMPO - SANTA MARIA',
        'CASPICHANGO - SANTA MARIA',
        'CERRO NEGRO - TINOGASTA',
        'CHAÑAR PUNCO - SANTA MARIA',
        'CHAQUIAGO - ANDALGALÁ',
        'CHISTIN - BELEN',
        'CHOYA - ANDALGALÁ',
        'CHUCHUCARUANA - AMBATO',
        'CHUMBICHA - CAPAYAN',
        'CHUQUISACA - TINOGASTA',
        'CIENAGA GRANDE - TINOGASTA',
        'COLANA - POMAN',
        'COLLAGASTA - FRAY MAMERTO ESQUIU',
        'COLONIA DEL VALLE - CAPAYAN',
        'COLONIA NUEVA CONETA - CAPAYAN',
        'COLPES - AMBATO',
        'COLPES - POMAN',
        'CONCEPCION - ANCASTI',
        'CONCEPCION - CAPAYAN',
        'CONDOR HUASI - ANDALGALÁ',
        'CONDOR HUASI - BELEN',
        'CONETA - CAPAYAN',
        'COPACABANA - TINOGASTA',
        'CORDOBITA - TINOGASTA',
        'CORRAL BLANCO - BELEN',
        'CORRAL DE PIEDRA - TINOGASTA',
        'CORRAL QUEMADO - BELEN',
        'CORTADERAS - SANTA ROSA',
        'COSTA DE REYES - TINOGASTA',
        'CUCHINOQUE - SANTA ROSA',
        'CUESTA DE VICUÑA PAMPA - BELEN',
        'CULAMPAJA - BELEN',
        'DOS POCITOS - SANTA ROSA',
        'EL ABRA - SANTA ROSA',
        'EL ALAMITO - ANDALGALÁ',
        'EL ALTO - EL ALTO',
        'EL AYBAL - LA PAZ',
        'EL BAÑADO - CAPAYAN',
        'EL BAÑADO - VALLE VIEJO',
        'EL BAÑADO - LA PAZ',
        'EL BASTIDOR - PACLIN',
        'EL BOLSON - AMBATO',
        'EL BOSQUECILLO - LA PAZ',
        'EL CAJON - SANTA MARIA',
        'EL CAJON - BELEN',
        'EL CARRIZAL - CAPAYAN',
        'EL CARRIZAL - BELEN',
        'EL CERCADO - LA PAZ',
        'EL CERRITO - SANTA MARIA',
        'EL CERRITO - LA PAZ',
        'EL CHAGUARAL - LA PAZ',
        'EL CLERIGO - LA PAZ',
        'EL COLEGIO - ANDALGALÁ',
        'EL COMEDERO - ANCASTI',
        'EL DESMONTE - SANTA MARIA',
        'EL DIQUE - LA PAZ',
        'EL DIVISADERO - LA PAZ',
        'EL DURAZNO - BELEN',
        'EL DURAZNO - TINOGASTA',
        'EL EJE - BELEN',
        'EL ESPINILLO - ANDALGALÁ',
        'EL HUAYCO - ANCASTI',
        'EL HUECO - FRAY MAMERTO ESQUIU',
        'EL JUMEAL - LA PAZ',
        'EL LINDERO - ANDALGALÁ',
        'EL MILAGRO - CAPAYAN',
        'EL MILAGRO - LA PAZ',
        'EL MISTOLITO - LA PAZ',
        'EL MOJON - ANCASTI',
        'EL MORENO - LA PAZ',
        'EL PAJONAL - POMAN',
        'EL PANTANILLO - EL ALTO',
        'EL PANTANILLO - CAPITAL',
        'EL PEÑON - ANTOFAGASTA DE LA SIERRA',
        'EL PORTEZUELO - VALLE VIEJO',
        'EL POTRERO - ANDALGALÁ',
        'EL POTRERO DE SAUJIL - POMAN',
        'EL POZO - BELEN',
        'EL PUCARA - ANDALGALÁ',
        'EL PUEBLITO - TINOGASTA',
        'EL PUESTO - SANTA MARIA',
        'EL PUESTO - TINOGASTA',
        'EL QUEBRACHAL - ANCASTI',
        'EL QUEBRACHITO - SANTA ROSA',
        'EL QUEMADO - CAPAYAN',
        'EL QUEMADO - ANDALGALÁ',
        'EL QUIMILO - LA PAZ',
        'EL RECREO - SANTA MARIA',
        'EL RETIRO - TINOGASTA',
        'EL RODEO - AMBATO',
        'EL ROSARIO - PACLIN',
        'EL ROSARIO - LA PAZ',
        'EL SALADO - TINOGASTA',
        'EL SAUCE - EL ALTO',
        'EL SAUCE - ANCASTI',
        'EL TACO - ANCASTI',
        'EL TALA - LA PAZ',
        'EL TALA - CAPITAL',
        'EL TALITA - ANCASTI',
        'EL TESORO - SANTA MARIA',
        'EL TOLAR - BELEN',
        'EL VALLECITO - LA PAZ',
        'EL VOLCAN - SANTA MARIA',
        'ENTRE RIOS - SANTA MARIA',
        'ESQUIU - LA PAZ',
        'ESTACION KILOMETRO 1017 - LA PAZ',
        'ESTACION KILOMETRO 969 - LA PAZ',
        'FAMABALASTO - SANTA MARIA',
        'FAMATANCA - SANTA MARIA',
        'FARALLON NEGRO - BELEN',
        'FIAMBALA - TINOGASTA',
        'FUERTE QUEMADO - SANTA MARIA',
        'GARAY - LA PAZ',
        'GUANACO YACO - POMAN',
        'GUAYAMBA - EL ALTO',
        'HUACO - BELEN',
        'HUACO - ANDALGALÁ',
        'HUALFIN - BELEN',
        'HUASI CIENAGA - BELEN',
        'HUAYCAMA - VALLE VIEJO',
        'HUAYCAMA - AMBATO',
        'HUILLAPIMA - CAPAYAN',
        'HUMAYA - AMBATO',
        'ICAÑO - LA PAZ',
        'ILOGA - EL ALTO',
        'INCAHUASI - ANTOFAGASTA DE LA SIERRA',
        'INFANZON - EL ALTO',
        'IPIZCA - ANCASTI',
        'ISLA LARGA - AMBATO',
        'JACIPUNCO - BELEN',
        'JOYANGO - POMAN',
        'LA AGUADA - ANDALGALÁ',
        'LA AGUADA - BELEN',
        'LA AGUADA DE LA TOMA - BELEN',
        'LA AGUADITA - TINOGASTA',
        'LA AGUADITA - BELEN',
        'LA ALBIGASTA - LA PAZ',
        'LA ANTIGUA - LA PAZ',
        'LA BAJADA - PACLIN',
        'LA BAJADA - SANTA ROSA',
        'LA BANDA - TINOGASTA',
        'LA BARRANQUITA - LA PAZ',
        'LA CALERA - CAPITAL',
        'LA CALERA - EL ALTO',
        'LA CANDELARIA - ANCASTI',
        'LA CARRERA - FRAY MAMERTO ESQUIU',
        'LA CERRILLADA - LA PAZ',
        'LA CHILCA - TINOGASTA',
        'LA CIENAGA - BELEN',
        'LA CIENAGA - TINOGASTA',
        'LA CIENAGA DE ABAJO - BELEN',
        'LA CIENAGA DE ARRIBA - BELEN',
        'LA CIENAGA REDONDA - ANTOFAGASTA DE LA SIERRA',
        'LA CUESTA - BELEN',
        'LA DORADA - LA PAZ',
        'LA ESTANCIA - BELEN',
        'LA ESTANCITA - ANCASTI',
        'LA FALDA - ANCASTI',
        'LA FALDA DE SAN ANTONIO - FRAY MAMERTO ESQUIU',
        'LA GRUTA - CAPITAL',
        'LA GUARDIA - LA PAZ',
        'LA HIGUERA - PACLIN',
        'LA HORQUETA - LA PAZ',
        'LA HORQUETA DE ARRIBA - LA PAZ',
        'LA HOYADA - SANTA MARIA',
        'LA HUERTA - EL ALTO',
        'LA ISLA - TINOGASTA',
        'LA ISLA - ANDALGALÁ',
        'LA LIBERTAD - CAPAYAN',
        'LA LOMA - SANTA MARIA',
        'LA MAJADA - ANCASTI',
        'LA MERCED - PACLIN',
        'LA MESADA - ANDALGALÁ',
        'LA OVEJERIA - SANTA MARIA',
        'LA PARADA - LA PAZ',
        'LA PARAGUAYA - CAPAYAN',
        'LA PERLA - POMAN',
        'LA PUERTA - AMBATO',
        'LA PUERTA DE TATON - TINOGASTA',
        'LA PUERTA SUD - AMBATO',
        'LA PUNTILLA - BELEN',
        'LA PUNTILLA - TINOGASTA',
        'LA PUNTILLA - SANTA MARIA',
        'LA QUEBRADA - SANTA MARIA',
        'LA QUINTA - LA PAZ',
        'LA RAMADITA - TINOGASTA',
        'LA RENOVACION - LA PAZ',
        'LA REPRESA - BELEN',
        'LA SALVIA - AMBATO',
        'LA SOLEDAD - SANTA MARIA',
        'LA SOLEDAD - TINOGASTA',
        'LA SUERTE - LA PAZ',
        'LA TERCENA - FRAY MAMERTO ESQUIU',
        'LA TOMA - BELEN',
        'LA TUNA - EL ALTO',
        'LA VIÑA - PACLIN',
        'LA ZANJA - LA PAZ',
        'LAGUNA BLANCA - BELEN',
        'LAMPACITO - SANTA MARIA',
        'LAS ANIMAS - CAPAYAN',
        'LAS BARRANCAS - BELEN',
        'LAS BREAS - CAPAYAN',
        'LAS CAÑAS - SANTA ROSA',
        'LAS CASITAS - POMAN',
        'LAS CHACRAS - TINOGASTA',
        'LAS CHACRITAS - AMBATO',
        'LAS CUEVAS - BELEN',
        'LAS CUEVAS - ANTOFAGASTA DE LA SIERRA',
        'LAS ESQUINAS - LA PAZ',
        'LAS ESQUINAS - VALLE VIEJO',
        'LAS FLORES - LA PAZ',
        'LAS GRANADILLAS - BELEN',
        'LAS HIGUERITAS - SANTA ROSA',
        'LAS HIGUERITAS - TINOGASTA',
        'LAS IGUANAS - LA PAZ',
        'LAS JUNTAS - AMBATO',
        'LAS JUNTAS - ANCASTI',
        'LAS JUNTAS - BELEN',
        'LAS LAJAS - PACLIN',
        'LAS LOMAS - BELEN',
        'LAS MOJARRAS - SANTA MARIA',
        'LAS PALMAS - CAPAYAN',
        'LAS PALMITAS - LA PAZ',
        'LAS PAMPITAS - ANDALGALÁ',
        'LAS PAPAS - TINOGASTA',
        'LAS QUINUAS - ANTOFAGASTA DE LA SIERRA',
        'LAS TEJAS - LA PAZ',
        'LAS TEJAS - VALLE VIEJO',
        'LAS TOSCAS - LA PAZ',
        'LAS TUNAS - SANTA ROSA',
        'LAS VALLAS - BELEN',
        'LAVALLE - SANTA ROSA',
        'LOCONTE - BELEN',
        'LONDRES - BELEN',
        'LORO HUASI - SANTA MARIA',
        'LORO HUASI - BELEN',
        'LOS ALAMOS - EL ALTO',
        'LOS ALTOS - SANTA ROSA',
        'LOS ANGELES NORTE - CAPAYAN',
        'LOS ANGELES SUR - CAPAYAN',
        'LOS ARBOLITOS - VALLE VIEJO',
        'LOS BALVERDIS - TINOGASTA',
        'LOS BAZAN - CAPAYAN',
        'LOS BULACIOS - ANCASTI',
        'LOS CASTILLOS - AMBATO',
        'LOS CERRILLOS - SANTA MARIA',
        'LOS CHAÑARITOS - CAPAYAN',
        'LOS CIENAGOS - POMAN',
        'LOS CORRALES - EL ALTO',
        'LOS MOGOTES - ANCASTI',
        'LOS MOLLES - ANCASTI',
        'LOS MOLLES - SANTA ROSA',
        'LOS MORTEROS - EL ALTO',
        'LOS NACIMIENTOS - ANTOFAGASTA DE LA SIERRA',
        'LOS NACIMIENTOS - BELEN',
        'LOS OSORES - EL ALTO',
        'LOS PALACIOS - TINOGASTA',
        'LOS PEDRAZA - EL ALTO',
        'LOS POCITOS - CAPAYAN',
        'LOS POZOS - EL ALTO',
        'LOS ROBLEDOS - TINOGASTA',
        'LOS SALTOS - SANTA MARIA',
        'LOS TALAS - AMBATO',
        'LOS TRONCOS - SANTA ROSA',
        'LOS VARELA - AMBATO',
        'LUNA AGUADA - BELEN',
        'MADERERA SAN ANTONIO - POMAN',
        'MANANTIALES - SANTA ROSA',
        'MARIA ELENA - LA PAZ',
        'MEDANITOS - SANTA MARIA',
        'MEDANITOS - TINOGASTA',
        'MINA CAPILLITAS - ANDALGALÁ',
        'MINAS DE CULAMPAJA - BELEN',
        'MIRAFLORES - CAPAYAN',
        'MONTE POTRERO - PACLIN',
        'MONTE REDONDO - SANTA ROSA',
        'MUTQUIN - POMAN',
        'NAVAGUIN - ANCASTI',
        'OVEJERIA - SANTA MARIA',
        'OYOLA - EL ALTO',
        'PAJANGUILLO - SANTA MARIA',
        'PALO BLANCO - TINOGASTA',
        'PALO CRUZ - LA PAZ',
        'PALO CRUZ DE ABAJO - LA PAZ',
        'PALO LABRADO - PACLIN',
        'PALO PARADO - LA PAZ',
        'PALO SANTO - LA PAZ',
        'PALO SECO - SANTA MARIA',
        'PALOMA YACO - SANTA MARIA',
        'PAMPA BLANCA - TINOGASTA',
        'PAMPA POZO - LA PAZ',
        'PAPA CHACRA - BELEN',
        'PIEDRA LARGA - BELEN',
        'PIPANACO - POMAN',
        'POLCOS - VALLE VIEJO',
        'POMAN - POMAN',
        'POMANCILLO - FRAY MAMERTO ESQUIU',
        'POMANCILLO ESTE - FRAY MAMERTO ESQUIU',
        'POMANCILLO OESTE - FRAY MAMERTO ESQUIU',
        'PORTILLO CHICO - LA PAZ',
        'POTRERO DE LOS CORDOBA - ANCASTI',
        'POZANCONES - LA PAZ',
        'POZO DE LA ORILLA - LA PAZ',
        'POZO DE PIEDRA - BELEN',
        'POZO DEL BAJO - SANTA ROSA',
        'POZO DEL CAMPO - SANTA ROSA',
        'POZO DEL MISTOL - VALLE VIEJO',
        'POZO LINDO - CAPAYAN',
        'PUERTA DE CORDOBA - LA PAZ',
        'PUERTA DE CORRAL QUEMADO - BELEN',
        'PUERTA DE MOLLE YACO - EL ALTO',
        'PUERTA DE SAN JOSE - BELEN',
        'PUERTA GRANDE - SANTA ROSA',
        'PUESTO DE RUA - CAPAYAN',
        'PUESTO DEL MEDIO - SANTA ROSA',
        'PUESTO NUEVO - CAPAYAN',
        'PUNTA DE BALASTO - SANTA MARIA',
        'PUNTA DEL AGUA - ANDALGALÁ',
        'PUNTA DEL AGUA - TINOGASTA',
        'QUEBRADA DE HUALFIN - BELEN',
        'QUEBRADA DE JUJUY - SANTA MARIA',
        'QUIROS - LA PAZ',
        'RAMBLONES - LA PAZ',
        'RECREO - SANTA MARIA',
        'RECREO - LA PAZ',
        'RINCO DE IPIZCA - ANCASTI',
        'RINCON - POMAN',
        'RIO CHICO - LA PAZ',
        'RIO CHICO - ANCASTI',
        'RIO COLORADO - TINOGASTA',
        'RIO DE AVILA - EL ALTO',
        'RIO DE LA DORADA - LA PAZ',
        'RIO DE LAS CASAS VIEJAS - AMBATO',
        'RIO DE LAS CUEVAS - BELEN',
        'RIO DEL MISTOLITO - LA PAZ',
        'RIO GRANDE - TINOGASTA',
        'RIO POTRERO - ANDALGALÁ',
        'RODEO GERVAN - BELEN',
        'SALAUCA - SANTA ROSA',
        'SAN AGUSTIN - LA PAZ',
        'SAN ANTONIO - FRAY MAMERTO ESQUIU',
        'SAN ANTONIO - LA PAZ',
        'SAN ANTONIO - PACLIN',
        'SAN ANTONIO - BELEN',
        'SAN BERNARDO - LA PAZ',
        'SAN FERNANDO - BELEN',
        'SAN FERNANDO DEL VALLE DE CATAMARCA - CAPITAL',
        'SAN FERNANDO NORTE - BELEN',
        'SAN FRANCISCO - ANCASTI',
        'SAN ISIDRO - VALLE VIEJO',
        'SAN ISIDRO - LA PAZ',
        'SAN JOSE - FRAY MAMERTO ESQUIU',
        'SAN JOSE - ANCASTI',
        'SAN JOSE - LA PAZ',
        'SAN JOSE BANDA - SANTA MARIA',
        'SAN JOSE DE COLPES - POMAN',
        'SAN JOSE NORTE - SANTA MARIA',
        'SAN JOSE VILLA - SANTA MARIA',
        'SAN LORENZO - LA PAZ',
        'SAN MARTIN - CAPAYAN',
        'SAN MIGUEL - LA PAZ',
        'SAN MIGUEL - TINOGASTA',
        'SAN MIGUEL - POMAN',
        'SAN NICOLAS - LA PAZ',
        'SAN PABLO - CAPAYAN',
        'SAN PEDRO - CAPAYAN',
        'SAN PEDRO - LA PAZ',
        'SAN PEDRO - SANTA ROSA',
        'SAN PEDRO - TINOGASTA',
        'SAN RAFAEL - LA PAZ',
        'SAN SALVADOR - LA PAZ',
        'SANTA BARBARA - PACLIN',
        'SANTA CRUZ - VALLE VIEJO',
        'SANTA CRUZ - TINOGASTA',
        'SANTA LUCIA - LA PAZ',
        'SANTA MARIA - SANTA MARIA',
        'SANTA MARTA - LA PAZ',
        'SANTA ROSA - LA PAZ',
        'SANTA ROSA - VALLE VIEJO',
        'SANTA ROSA - TINOGASTA',
        'SANTO DOMINGO - LA PAZ',
        'SAUCE HUACHO - EL ALTO',
        'SAUJIL - POMAN',
        'SAUJIL - TINOGASTA',
        'SIJAN - POMAN',
        'SINGUIL - AMBATO',
        'SISI HUASI - CAPAYAN',
        'SUMALAO - VALLE VIEJO',
        'SUMAMPA - PACLIN',
        'TACANA - ANCASTI',
        'TALAMAYO - BELEN',
        'TAPSO - EL ALTO',
        'TATON - TINOGASTA',
        'TELARITOS - CAPAYAN',
        'TIERRA VERDE - PACLIN',
        'TINOGASTA - TINOGASTA',
        'TINTIGASTA - EL ALTO',
        'TRAMPASACHA - CAPAYAN',
        'TUCUMANAO - POMAN',
        'VILISMAN - EL ALTO',
        'VILLA COLLANTES - PACLIN',
        'VILLA DE BALCOZNA - PACLIN',
        'VILLA DOLORES - VALLE VIEJO',
        'VILLA LAS PIRQUITAS - FRAY MAMERTO ESQUIU',
        'VILLA LUJAN - TINOGASTA',
        'VILLA SAN JOSE - BELEN',
        'VILLA SAN ROQUE - TINOGASTA',
        'VILLA VIL - BELEN',
        'VINQUIS - TINOGASTA',
        'VIS VIS - ANDALGALÁ',
        'YAPES - SANTA MARIA',
        'YERBA BUENA - ANCASTI',
        'ZAPICRUZ - POMAN',
        'ZARCITO - BELEN'
    ]
};
